### PR TITLE
send properties with queue build request

### PR DESCRIPTION
**Pull request by thomaswdean**
Please review these changes to allow properties to be sent with the build request

### CODE REVIEW

**Comment by thomaswdean** [comment]
@apxltd I was wondering if this PR has been seen and might make it into a new version of this extension.

**Comment by apxltd** [comment]
Shoot, sorry; I don:t think we received the notice. Looking now...

**Comment by apxltd** [comment]
Fixes #56

**Comment by apxltd** [comment]
@thomaswdean it all seemed pretty straight forward here's a pre-release build; I don't have a way to easily test the change, but it seems like it's not going to make it any worse, since it clearly wasn't sending those props before.

https://proget.inedo.com/feeds/PrereleaseExtensions/inedox/TeamCity/1.3.4-CI.1

Anyways I'll run a quick test here as well, and we'll get this published. Thanks so much for your help!! I think you can still comment here, even though it's closeD? Anyways let me know if it works :)

**Comment by thomaswdean** [comment]
@apxltd Thank you. I will switch to your pre-release build. I created my own upack the other day and have been using that so I already know that it works with this change.

**Comment by thomaswdean** [comment]
@apxltd Your pre-release build is working as expected. Thank you.

**Comment by apxltd** [comment]
Great, thanks much! It’s pre-release no more :)

**Pull request merged**
